### ISSUE TITLE
 ScanImageTiffReader not working for this tiff type, using tifffile

### ISSUE THREAD

**Issue by AntoineMal** [MouseLand/suite2p#900]
Hello everyone!

I have some trouble with the GUI. When I load my tif files I get this Error message...Does someone encounter something similar?

Thanks for the help!

Cheers,

Antoine

tif
** Found 1 tifs - converting to binary **
NOTE: ScanImageTiffReader not working for this tiff type, using tifffile
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\antoi\anaconda3\envs\suite2p\lib\runpy.py", line 194, in _run_module_as_main
>>>ERROR<<<
    return _run_code(code, main_globals, None,
  File "C:\Users\antoi\anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "C:\Users\antoi\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
    main()
  File "C:\Users\antoi\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
    run_s2p(ops, db)
  File "C:\Users\antoi\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 394, in run_s2p
    ops0 = io.tiff_to_binary(ops.copy())
  File "C:\Users\antoi\anaconda3\envs\suite2p\lib\site-packages\suite2p\io\tiff.py", line 148, in tiff_to_binary
    im = imread(file, pages=range(ix, ix + nfr))
  File "C:\Users\antoi\anaconda3\envs\suite2p\lib\site-packages\tifffile\tifffile.py", line 987, in imread
>>>ERROR<<<
    raise TypeError(
TypeError: imread() got unexpected keyword arguments 'pages'
Interrupted by error (not finished)

**Comment by vrutten** [comment]
Hi Antoine,
I ran into the same issue and it turns out that it's due to a recent deprecation by tifffile. 
If you downgrade your tifffile package to version 2022.5.4 it should run fine. 
Hope that fixes it for you too :)

**Comment by AntoineMal** [comment]
Hi!

Thanks four your answer! I solved my problem by manually deletet the input 'pages'.
I should probably try you way to be sure I didn't break anything  haha,

Thank you so much!
Have a wonderful monday! :)

**Comment by chriski777** [comment]
Hi folks, in the fix for #831, we updated suite2p so that the `pages` param is replaced by the `key` params (this replaces the deprecated `pages` in the latest tifffile version) `imread`. So, you could also update suite2p to the latest version on the main branch and I believe that will fix this issue too! Seems this issue has been resolved though so I will close this for now!

**Comment by AntoineMal** [comment]
Hey Chris!

Thanks for you reply. However, even if I have the last version of suite2p (v.0.11.1), I still get the same trouble... 
Maybe I'm doing something wrong but I don't really know what to do to correctly fix that problem...

**Comment by chriski777** [comment]
Ah yes, this change hasn't been included yet in the latest release (v0.11.1). It is however in the latest version of the `main` branch. You could install it using `pip install git+https://github.com/MouseLand/suite2p.git`! The version once you download this should be `0.11.2.dev47+gd7915fa`.
